# **Install Dependencies**

In [ ]:
!pip uninstall -y torch torchvision torchtext torchaudio

In [ ]:
""" This Versions are not available & they are Removed!"""
# !pip install torch==2.1.0+cu121 torchvision==0.16.0 torchaudio==2.1.0 --index-url https://download.pytorch.org/whl/cu121
# !pip install torchtext==0.16.0

In [4]:
"""
Reinstall PyTorch and related libraries with CUDA 12.1 support.
Note: Older versions (e.g., torch==2.1.0+cu121, torchtext==0.16.0) are no longer available.
This cell installs the earliest available compatible versions:
These versions are officially matched and stable to work together.
"""

# Install torch 2.2.0 + cu121 with compatible versions
!pip install torch==2.2.0+cu121 torchvision==0.17.0 torchaudio==2.2.0 --index-url https://download.pytorch.org/whl/cu121
# Install torchtext that matches torch 2.2.0
!pip install torchtext==0.16.2

Looking in indexes: https://download.pytorch.org/whl/cu121
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 757.2/757.2 MB 1.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 94.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 69.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 82.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 43.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 77.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 2.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 4.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 7.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 12.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 7.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196

In [ ]:
!pip install "numpy<2"

In [ ]:
# !pip install torchmetrics

In [ ]:
# !pip install torchdata

---
# **Import Library**

In [9]:
import torch
import torchtext

In [7]:
print("Torch version:", torch.__version__)
print("Torchtext version:", torchtext.__version__)
print("CUDA available:", torch.cuda.is_available())


Torch version: 2.2.0+cu121
Torchtext version: 0.16.2+cpu
CUDA available: False


---
# **GPU**

In [ ]:
!nvidia-smi

Thu Aug 14 18:03:08 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.94                 Driver Version: 560.94         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   43C    P3             10W /   35W |       0MiB /   6144MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

---
# **Dataset**

In [ ]:
!pip install portalocker

# Restart the runtime (important, otherwise torchtext still sees None)
import os, sys
os.kill(os.getpid(), 9)

In [1]:
from torchtext import datasets

In [2]:
train_set, test_set = datasets.AG_NEWS(root='/content/', split=('train', 'test'))

In [3]:
train_set, test_set

(ShardingFilterIterDataPipe, ShardingFilterIterDataPipe)

- **NLP Datasets:** ``` Iterable DataPipes```
- **Computer Vision Datasets:** ```Map-Style DataPipes```

In [4]:
next(iter(train_set))

(3,
 "Wall St. Bears Claw Back Into the Black (Reuters) Reuters - Short-sellers, Wall Street's dwindling\\band of ultra-cynics, are seeing green again.")

In [ ]:
train_iter = iter(train_set)
print(train_iter)

<generator object ShardingFilterIterDataPipe.__iter__ at 0x7b38092c3740>


In [ ]:
next(train_iter)

(3,
 "Oil and Economy Cloud Stocks' Outlook (Reuters) Reuters - Soaring crude prices plus worries\\about the economy and the outlook for earnings are expected to\\hang over the stock market next week during the depth of the\\summer doldrums.")

In [ ]:
next(train_iter)

(3,
 'Carlyle Looks Toward Commercial Aerospace (Reuters) Reuters - Private investment firm Carlyle Group,\\which has a reputation for making well-timed and occasionally\\controversial plays in the defense industry, has quietly placed\\its bets on another part of the market.')

> ## Convert to Map-Style DataPipes/Dataset

In [ ]:
from torchtext.data import to_map_style_dataset
from torchtext.data.functional import to_map_style_dataset

In [ ]:
# load the Dataset
train_set_MapStyle, test_set_MapStyle = datasets.AG_NEWS(root='/content/', split=('train', 'test'))

# Convert the iterable dataset to Map-Style Dataset
train_set_MapStyle = to_map_style_dataset(train_set_MapStyle)
test_set_MapStyle = to_map_style_dataset(train_set_MapStyle)

In [163]:
for i in range(10):
    print(train_set_MapStyle[i])

(3, "Wall St. Bears Claw Back Into the Black (Reuters) Reuters - Short-sellers, Wall Street's dwindling\\band of ultra-cynics, are seeing green again.")
(3, 'Carlyle Looks Toward Commercial Aerospace (Reuters) Reuters - Private investment firm Carlyle Group,\\which has a reputation for making well-timed and occasionally\\controversial plays in the defense industry, has quietly placed\\its bets on another part of the market.')
(3, "Oil and Economy Cloud Stocks' Outlook (Reuters) Reuters - Soaring crude prices plus worries\\about the economy and the outlook for earnings are expected to\\hang over the stock market next week during the depth of the\\summer doldrums.")
(3, 'Iraq Halts Oil Exports from Main Southern Pipeline (Reuters) Reuters - Authorities have halted oil export\\flows from the main pipeline in southern Iraq after\\intelligence showed a rebel militia could strike\\infrastructure, an oil official said on Saturday.')
(3, 'Oil prices soar to all-time record, posing new menace t

---

# **DataLoader**

> ### BERT Tokenizer

In [18]:
from torchtext.transforms import BERTTokenizer

VOCAB_FILE = "https://huggingface.co/bert-base-uncased/resolve/main/vocab.txt"

tokenizer_BERT = BERTTokenizer(vocab_path=VOCAB_FILE,
                               do_lower_case=True,
                               return_tokens=True)
tokenizer_BERT

100%|██████████| 232k/232k [00:00<00:00, 5.36MB/s]


BERTTokenizer()

> ### GloVe Vectorization

In [33]:
from torchtext.vocab import GloVe

vectorization = GloVe(name="6B", dim=100)
vectorization

.vector_cache/glove.6B.zip: 862MB [06:40, 2.15MB/s]                           
100%|█████████▉| 399999/400000 [00:26<00:00, 15090.82it/s]


In [43]:
vectorization.get_vecs_by_tokens(tokenizer_BERT('Hello World, How are you!')).shape

torch.Size([7, 100])

> ### Bulid the DataLoader Structure

In [5]:
from torch.utils.data import DataLoader

#### *1st Output Try*

In [30]:
def collate(batchs):
    # extract & define labels in range of 0 to 3
    labels = torch.LongTensor([batch[0] for batch in batchs]) - 1
    # extract texts from the batch
    texts = [batch[1] for batch in batchs]

    return texts, labels


In [31]:
train_loader = DataLoader(train_set, batch_size=2, shuffle=True, collate_fn=collate)
test_loader = DataLoader(test_set, batch_size=128, shuffle=False)

In [10]:
next(iter(train_loader))

(['U.S. Signals Flexibility on Israeli Settlement Growth  CRAWFORD, Texas (Reuters) - The Bush administration  signaled on Saturday that it may accept limited growth within  existing Israeli settlements in the West Bank in a shift that  could help embattled Prime Minister Ariel Sharon.',
  'Content software targets small publishers Snapbridge Software brings content management to the little guys.'],
 tensor([0, 3]))

#### *2nd Output Try - Final*

In [ ]:
from torch.nn.utils.rnn import pad_sequence

In [130]:
def collate(batchs):
    # extract & define labels in range of 0 to 3
    labels = torch.LongTensor([batch[0] for batch in batchs]) - 1
    # extract texts from the batch
    texts = [batch[1] for batch in batchs]

    # tokenize the textx using BERT Tokenizer
    tokens = tokenizer_BERT(texts)
    num_tokens = len(tokens)
    vectors = []

    # Vectorization the tokens using GloVe
    # vectors.append(vectorization.get_vecs_by_tokens(text_tokens) for text_tokens in tokens)
    for i in range(num_tokens):

        # vectorization of the tokens in batch
        vectors.append(vectorization.get_vecs_by_tokens(tokens[i]))

    # Pad the sequences to the maximum length in the batch
    padded_vectors = pad_sequence(vectors, batch_first=False, padding_value=0.0)

    return  padded_vectors, labels

In [149]:
# Creat Train & Test Loader with ```collate```
train_loader = DataLoader(train_set, batch_size=24, shuffle=True, collate_fn=collate)
test_loader = DataLoader(test_set, batch_size=128, shuffle=False, collate_fn=collate)

##### ```Train Loader```

In [143]:
# Check the TrainLoader
x, y = next(iter(train_loader))

# Display the Reults
print("--- Text Vectorization Results ---")
print("Shape: ", x.shape)
print(x)

print(80*"=")

print("--- Labels ---")
print(y)
print("Shape of Lables: ", y.shape)

--- Text Vectorization Results ---
Shape:  torch.Size([153, 24, 100])
tensor([[[-0.3099, -0.1162,  0.2945,  ..., -0.0364,  0.2119, -0.2907],
         [ 0.6621,  0.0665,  0.3640,  ..., -0.1493, -0.4993,  0.1637],
         [-0.1659,  0.3444,  1.1095,  ...,  0.6920,  0.2801,  0.2384],
         ...,
         [-0.0382, -0.2449,  0.7281,  ..., -0.1459,  0.8278,  0.2706],
         [-0.0311,  0.2216,  0.4449,  ..., -0.6710,  0.2470, -0.6200],
         [-0.5261, -0.0670, -0.1735,  ..., -0.7912,  0.0476,  0.0844]],

        [[-0.1786,  0.1492,  0.5122,  ...,  0.3148,  0.5245,  0.1552],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         ...,
         [-0.0440,  0.1894,  0.6611,  ..., -0.1417,  0.9279,  0.5906],
         [-0.3398,  0.2094,  0.4635,  ..., -0.2339,  0.4730, -0.0288],
         [-1.2557,  0.6104,  0.5679,  ..., -1.5877,  0.7698, -0.6500]],

        [[ 0.0587,  0.6981,  0.4263,  ..., -0.

##### ```Test Loader```

In [150]:
# Check the Test Loader
x, y = next(iter(test_loader))

# Display the Reults
print("--- Text Vectorization Results ---")
print("Shape: ", x.shape)
print(x)

print(80*"=")

print("--- Labels ---")
print(y)
print("Shape of Lables: ", y.shape)

--- Text Vectorization Results ---
Shape:  torch.Size([198, 128, 100])
tensor([[[ 0.1792,  0.3733,  0.5073,  ..., -0.0049, -0.0746,  0.0169],
         [-0.0382, -0.2449,  0.7281,  ..., -0.1459,  0.8278,  0.2706],
         [-0.9662, -0.0946,  0.9061,  ..., -1.2542,  0.8202, -0.2788],
         ...,
         [-0.1672,  0.0434,  1.1972,  ...,  0.0957,  1.0813, -0.1622],
         [-0.5481, -0.5953,  0.5111,  ...,  0.0444,  0.3507,  0.5338],
         [ 0.1110, -0.1874,  0.7070,  ...,  0.4406,  0.6769,  0.1460]],

        [[-0.1440,  0.3255,  0.1426,  ...,  0.2540,  1.1078, -0.0731],
         [ 0.4801,  0.1466,  0.7959,  ...,  0.3337,  1.0150,  0.0887],
         [-0.3398,  0.2094,  0.4635,  ..., -0.2339,  0.4730, -0.0288],
         ...,
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [-0.1889,  0.0375,  0.8074,  ...,  0.3299, -0.5725,  0.0508],
         [ 0.6625,  0.0465,  0.6582,  ...,  0.0321,  0.7238,  0.3681]],

        [[ 0.1348,  0.4022, -0.4227,  ..., -0

---
# **Pre-Process**

> ## Tokenizer



In [12]:
from torchtext.data.utils import get_tokenizer
tokenizer = get_tokenizer("basic_english")

In [ ]:
test_sentence = "This is a test sentence."
tokens = tokenizer(test_sentence)
print(tokens)
print("Number of tokens:", len(tokens))

['this', 'is', 'a', 'test', 'sentence', '.']
Number of tokens: 6


In [ ]:
split = test_sentence.split()
print(split)
print("Number of split tokens:", len(split))

['This', 'is', 'a', 'test', 'sentence.']
Number of split tokens: 5


As the below Result shows, using the tokenizer ```basic_english``` can tokenize the text very well in comparison to command ```split``` that couldn't tokenize somthing like ., !, ?, ...

> ## Vectorization

In [ ]:
from torchtext.vocab import GloVe
from torchtext.vocab import build_vocab_from_iterator

### GloVe

In [ ]:
vectorization = GloVe(name="6B", dim=100)
vectorization

In [ ]:
vectorization.itos[:11]

['the', ',', '.', 'of', 'to', 'and', 'in', 'a', '"', "'s", 'for']

In [ ]:
vectorization.stoi["and"]

5

In [ ]:
vectorization.stoi

{'the': 0,
 ',': 1,
 '.': 2,
 'of': 3,
 'to': 4,
 'and': 5,
 'in': 6,
 'a': 7,
 '"': 8,
 "'s": 9,
 'for': 10,
 '-': 11,
 'that': 12,
 'on': 13,
 'is': 14,
 'was': 15,
 'said': 16,
 'with': 17,
 'he': 18,
 'as': 19,
 'it': 20,
 'by': 21,
 'at': 22,
 '(': 23,
 ')': 24,
 'from': 25,
 'his': 26,
 "''": 27,
 '``': 28,
 'an': 29,
 'be': 30,
 'has': 31,
 'are': 32,
 'have': 33,
 'but': 34,
 'were': 35,
 'not': 36,
 'this': 37,
 'who': 38,
 'they': 39,
 'had': 40,
 'i': 41,
 'which': 42,
 'will': 43,
 'their': 44,
 ':': 45,
 'or': 46,
 'its': 47,
 'one': 48,
 'after': 49,
 'new': 50,
 'been': 51,
 'also': 52,
 'we': 53,
 'would': 54,
 'two': 55,
 'more': 56,
 "'": 57,
 'first': 58,
 'about': 59,
 'up': 60,
 'when': 61,
 'year': 62,
 'there': 63,
 'all': 64,
 '--': 65,
 'out': 66,
 'she': 67,
 'other': 68,
 'people': 69,
 "n't": 70,
 'her': 71,
 'percent': 72,
 'than': 73,
 'over': 74,
 'into': 75,
 'last': 76,
 'some': 77,
 'government': 78,
 'time': 79,
 '$': 80,
 'you': 81,
 'years': 82,
 'i

### Giving Tokens to GloVe


In [ ]:
vectorization.get_vecs_by_tokens(tokens)

tensor([[-5.7058e-01,  4.4183e-01,  7.0102e-01, -4.1713e-01, -3.4058e-01,
          2.3390e-02, -7.1537e-02,  4.8177e-01, -1.3121e-02,  1.6834e-01,
         -1.3389e-01,  4.0626e-02,  1.5827e-01, -4.4342e-01, -1.9403e-02,
         -9.6610e-03, -4.6284e-02,  9.3228e-02, -2.7331e-01,  2.2850e-01,
          3.3089e-01, -3.6474e-01,  7.8741e-02,  3.5850e-01,  4.4757e-01,
         -2.2990e-01,  1.8077e-01, -6.2650e-01,  5.3852e-02, -2.9154e-01,
         -4.2560e-01,  6.2903e-01,  1.4393e-01, -4.6004e-02, -2.1007e-01,
          4.8879e-01, -5.7698e-02,  3.7431e-01, -3.0075e-02, -3.4494e-01,
         -2.9702e-01,  1.5095e-01,  2.8248e-01, -1.6578e-01,  7.6131e-02,
         -9.3016e-02,  7.9365e-01, -6.0489e-01, -1.8874e-01, -1.0173e+00,
          3.1962e-01, -1.6344e-01,  5.4177e-01,  1.1725e+00, -4.7875e-01,
         -3.3842e+00, -8.1301e-02, -3.5280e-01,  1.8372e+00,  4.4516e-01,
         -5.2666e-01,  9.9786e-01, -3.2178e-01,  3.3462e-02,  1.1783e+00,
         -7.2905e-02,  3.9737e-01,  2.

In [ ]:
vectorization.get_vecs_by_tokens(tokens).shape

torch.Size([6, 100])

we had a sentence of "This is a test sentence." that the tokenizer, tokenize it to 6 token. Also we choose the "dim=100" for the GloVe.

So the output correctly shows the sape of vectorization [6, 100].


### Check the Vectorization Results of different Words

In [ ]:
vec_boy = vectorization.get_vecs_by_tokens('boy')
vec_girl = vectorization.get_vecs_by_tokens('girl')
vec_street = vectorization.get_vecs_by_tokens('street')

In [ ]:
import torch.nn.functional as F
print("--- Cosine Similarity ---")
print("boy VS. girl:", F.cosine_similarity(vec_boy, vec_girl, dim=0))
print("boy VS. street:", F.cosine_similarity(vec_boy, vec_street, dim=0))
print("girl VS. street:", F.cosine_similarity(vec_girl, vec_street, dim=0))

--- Cosine Similarity ---
boy VS. girl: tensor(0.9176)
boy VS. street: tensor(0.3859)
girl VS. street: tensor(0.3354)


As the results show, the vectorization outputs are correct because the `boy` and the `girl` are more similar to each other compared to the `street`, since both are human/family-related.

> ## Transform ( Optional - just for Test )

In [ ]:
import torchtext.transforms as T

- ### BERT Tokenizer

In [ ]:
VOCAB_FILE = "https://huggingface.co/bert-base-uncased/resolve/main/vocab.txt"

tokenizer_BERT = T.BERTTokenizer(vocab_path=VOCAB_FILE,
                            do_lower_case=True)

print("\n",tokenizer_BERT('Hello World, How are you!'))
print(tokenizer_BERT(['Hello World, How are you!', 'hi there.']))

100%|██████████| 232k/232k [00:00<00:00, 5.42MB/s]


 ['7592', '2088', '1010', '2129', '2024', '2017', '999']
[['7592', '2088', '1010', '2129', '2024', '2017', '999'], ['7632', '2045', '1012']]


In [ ]:
tokenizer_BERT = T.BERTTokenizer(vocab_path=VOCAB_FILE,
                            do_lower_case=True,
                            return_tokens=True)

print(tokenizer_BERT('Hello World, How are you!'))
print(tokenizer_BERT(['Hello World, How are you!', 'hi there.']))

100%|██████████| 232k/232k [00:00<00:00, 4.61MB/s]


['hello', 'world', ',', 'how', 'are', 'you', '!']
[['hello', 'world', ',', 'how', 'are', 'you', '!'], ['hi', 'there', '.']]


- ### ToTensor

In [ ]:
sent1 = 'hi there.'
sent2 = 'Hello World, How are you!'

In [ ]:
tokens = tokenizer_BERT([sent1, sent2])

token_ids1 = [vectorization.stoi[token] for token in tokens[0]]
token_ids2 = [vectorization.stoi[token] for token in tokens[1]]
token_ids = [token_ids1, token_ids2]
token_ids

[[11083, 63, 2], [13075, 85, 1, 197, 32, 81, 805]]

In [ ]:
to_tensor = T.ToTensor(padding_value=0)
to_tensor(token_ids)

tensor([[11083,    63,     2,     0,     0,     0,     0],
        [13075,    85,     1,   197,    32,    81,   805]])

- ### Truncate

In [ ]:
print(tokens[1])
T.Truncate(max_seq_len=3)(tokens[1])

['hello', 'world', ',', 'how', 'are', 'you', '!']


['hello', 'world', ',']

- ### Sequential

In [ ]:
tr = T.Sequential(T.BERTTokenizer(vocab_path=VOCAB_FILE,
                            do_lower_case=True,
                            return_tokens=True),
                  T.Truncate(max_seq_len=3))
tr

100%|██████████| 232k/232k [00:00<00:00, 5.49MB/s]


Sequential(
  (0): BERTTokenizer()
  (1): Truncate()
)

In [ ]:
print(sent2)
tr(sent2)

Hello World, How are you!


['hello', 'world', ',']

> ## Utils - Ngrams

In [ ]:
from torchtext.data.utils import ngrams_iterator

In [ ]:
sent3 = 'Return an iterator that yields the given tokens and their ngrams.'
tokens = tokenizer_BERT(sent3)
print(tokens)

['return', 'an', 'it', '##era', '##tor', 'that', 'yields', 'the', 'given', 'token', '##s', 'and', 'their', 'ng', '##ram', '##s', '.']


In [ ]:
sent3 = 'Return an iterator that yields the given tokens and their ngrams.'
tokens = tokenizer(sent3)
print(tokens)

['return', 'an', 'iterator', 'that', 'yields', 'the', 'given', 'tokens', 'and', 'their', 'ngrams', '.']


In [ ]:
ngrams_iterator(tokens, ngrams=3)

<generator object ngrams_iterator at 0x7a671c61f740>

In [ ]:
list(ngrams_iterator(tokens, ngrams=3))

['return',
 'an',
 'iterator',
 'that',
 'yields',
 'the',
 'given',
 'tokens',
 'and',
 'their',
 'ngrams',
 '.',
 'return an',
 'an iterator',
 'iterator that',
 'that yields',
 'yields the',
 'the given',
 'given tokens',
 'tokens and',
 'and their',
 'their ngrams',
 'ngrams .',
 'return an iterator',
 'an iterator that',
 'iterator that yields',
 'that yields the',
 'yields the given',
 'the given tokens',
 'given tokens and',
 'tokens and their',
 'and their ngrams',
 'their ngrams .']